sonar.projectKey=mrlachir_keyrak_api
sonar.organization=mrlachir

sonar.sources=backend/src/main/java

sonar.java.binaries=backend/target/classes

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/*Test.java
