import { describe, expect, it, vi } from "vitest";
import { signInErrorMessage, signInReturnPath } from "@/lib/sign-in";

vi.mock("@/lib/env", () => ({ requireServerEnv: () => "test-only-value" }));
vi.mock("@/lib/backend-token", () => ({ resolveBackendRole: vi.fn(), signBackendToken: vi.fn() }));
import { authOptions } from "@/lib/auth";

describe("custom authentication entry points", () => {
  it("replaces the built-in sign-in and error screens without changing Google OAuth", () => {
    expect(authOptions.pages).toEqual({ signIn: "/auth/signin", error: "/auth/signin" });
    expect(authOptions.providers[0].id).toBe("google");
  });

  it("preserves relative property review anchors and search query strings", () => {
    expect(signInReturnPath("/properties/a-property#reviews")).toBe("/properties/a-property#reviews");
    expect(signInReturnPath("/search?q=Quiet%20villa")).toBe("/search?q=Quiet%20villa");
  });

  it("accepts same-origin absolute callbacks generated by NextAuth", () => {
    expect(signInReturnPath("https://keyrak.example/properties/123#reviews", "https://keyrak.example"))
      .toBe("/properties/123#reviews");
  });

  it.each([
    undefined, ["/profile", "/admin"], "https://other.example/profile", "//other.example", "/\\other.example",
    "javascript:alert(1)", "/%2fother.example", "/%5cother.example", "/auth/signin", "/api/auth/signin?callbackUrl=/",
    "/search/../auth/signin", "/a\nlocation", "/%invalid", "profile",
  ])("rejects unsafe callbacks or auth loops: %s", value => {
    expect(signInReturnPath(value)).toBe("/");
  });

  it("uses friendly allowlisted messages, never raw error query text", () => {
    expect(signInErrorMessage(undefined)).toBeNull();
    expect(signInErrorMessage("Configuration")).toContain("temporarily unavailable");
    expect(signInErrorMessage("SessionRequired")).toContain("Please sign in");
    expect(signInErrorMessage("<script>secret</script>")).not.toContain("secret");
    expect(signInErrorMessage("__proto__")).toBeTypeOf("string");
  });
});
